version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nimble-photos-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nimble_photos_admin
      POSTGRES_PASSWORD: nimble_photos_password
      POSTGRES_DB: nimble_photos
    volumes:
      - photo-data:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nimble_photos_admin -d nimble_photos" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:9.11
    container_name: nimble-photos-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@nimblephotos.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5051:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - photo_pgadmin:/var/lib/pgadmin

volumes:
  photo-data:
  photo_pgadmin: