[package]
name = "nimble-photos"
version = "0.1.0"
edition = "2024"

[dependencies]
nimble-web = { path = "./crates/nimble-web" }
tokio = { version = "1.49", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
log = "0.4"
env_logger = "0.11"
async-trait = "0.1"
